---
- hosts: all
  vars:
  tasks:
    - name: get elasticsearch role
      local_action: git repo=https://github.com/elastic/ansible-elasticsearch.git dest=provisioning/roles/elasticsearch
      run_once: true

- hosts: all
  sudo: yes
  vars:
  tasks:
    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]
  roles:
    - { role: elasticsearch,
      es_config: {
        node.name: "${HOSTNAME}",
        cluster.name: "custom-cluster",
        network.host: [ "_local_", "_site_" ],
        discovery.zen.ping.unicast.hosts: "10.0.0.11, 10.0.0.12, 10.0.0.13",
        shield.ssl.keystore.path: '/etc/elasticsearch/{{ ansible_nodename }}/shield/{{ ansible_nodename }}.jks',
        shield.ssl.keystore.password: password,
        shield.ssl.truststore.path: '/etc/elasticsearch/{{ ansible_nodename }}/shield/truststore.jks',
        shield.ssl.truststore.password: password,
        shield.transport.ssl: true,
        shield.http.ssl: true,
        shield.ssl.hostname_verification.resolve_name: false,
        shield.ssl.ciphers: [ "TLS_RSA_WITH_AES_128_CBC_SHA256", "TLS_RSA_WITH_AES_128_CBC_SHA" ],
        shield.audit.enabled: true,
        shield.http.ssl.client.auth: required
      }
    }
  handlers:
