---
# intermediate setup
# - file: path={{ playbook_dir }}/certs/ca/intermediate state=directory
- file: path={{ playbook_dir }}/{{ item }} state=directory
  with_items:
    - certs/ca/intermediate/certs
    - certs/ca/intermediate/crl
    - certs/ca/intermediate/csr
    - certs/ca/intermediate/newcerts
    - certs/ca/intermediate/private

- file: path={{ playbook_dir }}/certs/ca/intermediate/index.txt state=touch
- copy: content="1000" dest="{{ playbook_dir }}/certs/ca/intermediate/serial"
- copy: content="1000" dest="{{ playbook_dir }}/certs/ca/intermediate/crlnumber"

- name: OpenSSL | Generate openssl Intermediate config file
  template: src=templates/openssl-intr.cnf.j2 dest={{ playbook_dir }}/certs/ca/intermediate/openssl-intr.cnf

- name: OpenSSL | Create Intermediate key
  command: 'openssl genrsa -aes256 -passout pass:{{ INTR_password }} \
    -out intermediate/private/intermediate.key.pem 4096'
  args:
    chdir: '{{ playbook_dir }}/certs/ca'
    creates: '{{ playbook_dir }}/certs/ca/intermediate/private/intermediate.key.pem'

- name: OpenSSL | Create Intermediate Cert Signing Request
  command: 'openssl req -config intermediate/openssl-intr.cnf -new -passin pass:{{ INTR_password }} \
    -subj "{{ INTR_CN }}" -sha256 -key intermediate/private/intermediate.key.pem \
    -out intermediate/csr/intermediate.csr.pem'
  args:
    chdir: '{{ playbook_dir }}/certs/ca'
    creates: '{{ playbook_dir }}/certs/ca/intermediate/csr/intermediate.csr.pem'

- name: OpenSSL | Sign Intermediate Cert Signing Request
  command: 'openssl ca -batch -config openssl-ca.cnf -extensions v3_intermediate_ca \
    -passin pass:{{ CA_password }} -days 3650 -notext -md sha256 \
    -in intermediate/csr/intermediate.csr.pem \
    -out intermediate/certs/intermediate.cert.pem'
  args:
    chdir: '{{ playbook_dir }}/certs/ca'
    creates: '{{ playbook_dir }}/certs/ca/intermediate/certs/intermediate.cert.pem'

# Intermediate truststore
- name: Java Keytool | Truststore Intermediate
  command: 'keytool -importcert -noprompt -alias my_intr \
    -keystore truststore.jks  -storepass password -keypass password \
    -file {{ playbook_dir }}/certs/ca/intermediate/certs/intermediate.cert.pem'
  args:
    chdir: '{{ playbook_dir }}/certs/keytool'
  register: trust_intr
  changed_when: trust_intr.rc == 0
  ignore_errors: true
