---
# - file: path=certs state=directory
- name: Setup certs folder
  file: path={{ playbook_dir }}/certs/keytool state=directory

- include: CA.yml
- include: Intermediate.yml
- include: Node_Certs.yml
